BBBBBBB BBBBBBBBBBBBBBBBB
BBBBB BBBB XXXXXX XXXXXXX X XXXXXXX XXXX BBBBBBBB

BBBBB BBBBBBB


XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX
        XXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXXX  XXXXXXXX
            XXXX
            BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXX
            BBBBBB
            XXXXX
        XXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXX XXXX
            XXXX
            BBB BBBB BB BBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBB
                    XXXXXXXXX
                BBBBB
            BBBBBB
            XXXXX
        XXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXX XXXXXX XXXX
        XXXX
        BBB BBBB BB BBBBBBBBBBBBBBBBBBBB
            XXXXXXXXX
            XXXX
            BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXX
            BBBBBB
            XXXXX
        BBBBBB
        XXXXX
        BBBB
        XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXX XX XXXX XXXXX XX XXXXXXXX
        XXXXXX XXXXX XXXX XX XXXXXXX XXXX XXX XXXXXXXXXXX
        BBBBB
    BBBB
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XX XXX XXXX XXXXXXXXXX

    XX XXXXXXBBB BBBBBBBXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
  XXXXXX
XXXXXX
BBBBBBBB
