BBBBBBB BBBBBBBBBBBBBBBBB
BBBBB BBBB XXXXXX XXXXXX X XXXXXX XXXX BBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX  XXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
    XXX XXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXX XXXXX XXXX
    XXXX
        XXXXXXX XXXXX XXXX
        XXXXXXXXXX XXXX
        XXXXXXX XXXXXX XXXX
    XXXXX
    BBBB
    XX XXXXXXXXXXXXXXXX XXXX XXXXXXXXX
    BBBBB
    XXX XXXXXXXXXXXXX
    BB BBBBBBBBB
    XX XXXXXXXXXXXXXXXXX XXXXXX XXXX
    XXXX
        BBB BBBB BB BBBBBBBBB
            XXXXXXX XXXXX XXXX
            XXXXXXX XXXXXX FFFFFFFFFFF FFFFXXXX
             #
 #

            XXXXXXX XXXX FFFFFFFFFFF FFFFXXXX
            XXX XXXXXXXXXXXXX

        BBBBBB
    XXXXX
    BBBBB
  XXXXXX
XXXXXX
BBBBBBBB
