BBBBBBB BBBBBBBBBBBBBBBBB
BBBBB BBBB XXX XXXXXXXX X XXXXXXXX XXXX BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX
    XXXX
        BBB BBBBBBB BB BBBBBBBB
            XXXXXXXXX
            XXX XXXXXXXXXXXXX
        BBBBBB
    XXXXX
  XXXXXX
XXXXXX
BBBBBBBB