BBBBBBB BBBBBBBBBBBBBBBBB
BBBBB BBBB XXXX XXXXXX X XXXX XXXX BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXX
            BBBBBBBBBB

            BBB BBBBB BB BBBB
                XXXX XXXXXXXXXXXXXXXXXXX
                    
                    
                XXXXXX
            BBBBBB

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB