BBBBBBB BBBBBBBBBBBBBBBBB
BBBBB BBBB XXXX XXXXXXX X XXXX XXXX BBBBBBBB

BBBBB BBBBBBB

  
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XX
      BB BBBBBBBBBBBBBBBBBBBBB
      BBB BBBBBBB BB BBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX
      XXXXXX
      BBBBBB
      BBBB
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XX XXX XXXX XXXXXXXXXX

      XX XXXXXXBBB BBBBBBBXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
  XXXXXX
XXXXXX

BBBBBBBB
