BBBBBBB BBBBBBBBBBBBBBBBB
BBBBB BBBB XXX XXXXXXX X XXXX XXXXXXX BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XX
        XXXX
            BBB BBBBBB BB BBBBBBB
                XXXX
                    XX XXXXXXXX XXXX
                XXXXX
            BBBBBB
        XXXXX
    XXXXXX
XXXXXX

BBBBBBBB