# Generated by Django 2.2.7 on 2019-11-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_place',
            old_name='job',
            new_name='worker',
        ),
    ]
