# Generated by Django 2.2.7 on 2019-12-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Cancelled')], default=1, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='work_place',
            name='is_copy',
            field=models.PositiveSmallIntegerField(choices=[(0, False), (1, True)], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='work_place',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Finished'), (1, 'New'), (2, 'Approved'), (3, 'Cancelled')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='work_place',
            name='worker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.Worker'),
        ),
        migrations.CreateModel(
            name='Fineshed_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='works.Work')),
                ('work_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='works.WorkTime')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='work_place',
            name='work_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.WorkTime'),
        ),
    ]
