# Generated by Django 2.2.7 on 2019-11-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20191125_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_place',
            name='work_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Work'),
        ),
        migrations.AlterField(
            model_name='work_place',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='works.Worker'),
        ),
    ]
