# Generated by Django 2.2.7 on 2019-11-25 12:58

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20191125_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_place',
            name='worker',
            field=models.OneToOneField(on_delete=models.SET(works.models.get_name), to='works.Worker'),
        ),
    ]
