# Generated by Django 2.2.7 on 2019-12-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20191202_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_active',
            field=models.PositiveSmallIntegerField(choices=[(0, False), (1, True)], default=0, max_length=1),
        ),
    ]
