# Generated by Django 2.2.7 on 2019-11-25 13:00

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20191125_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_place',
            name='work_name',
            field=models.ForeignKey(on_delete=models.SET(works.models.get_name), to='works.Work'),
        ),
    ]
