# Generated by Django 2.2.7 on 2019-12-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fineshed_work',
            new_name='FineshedWork',
        ),
        migrations.RenameModel(
            old_name='Work_place',
            new_name='WorkPlace',
        ),
    ]
