# Generated by Django 2.2.7 on 2019-12-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20191206_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='is_copy',
            field=models.BooleanField(default=False),
        ),
    ]
