# Generated by Django 2.2.7 on 2019-11-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20191125_1505'),
        ('works', '0003_auto_20191125_1511'),
    ]

    operations = [
    ]
