# Generated by Django 2.2.7 on 2019-12-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20191206_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='worker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.Worker'),
        ),
    ]
