# Generated by Django 2.2.7 on 2019-12-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_auto_20191206_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workplace',
            old_name='work_name',
            new_name='work',
        ),
        migrations.DeleteModel(
            name='FineshedWork',
        ),
    ]
