# Generated by Django 3.0 on 2019-12-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_auto_20191209_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='limit_hours',
            field=models.PositiveIntegerField(default=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplace',
            name='worker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='works.Worker'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='date_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('A', 'Approved'), ('C', 'Cancelled')], default='NEW', max_length=1),
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_weak', models.PositiveIntegerField()),
                ('work_time_in_weak', models.DateTimeField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='works.Worker')),
            ],
        ),
    ]
