# Generated by Django 3.0 on 2019-12-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_auto_20191216_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name',
        ),
    ]
